name: release

on:
  push:
    tags:
      - "v*"

env:
  dotnet: 3.1.201
  version: 7.9.0

jobs:
  win:
    runs-on: ubuntu-latest
    name: build win
    steps:
      - uses: actions/checkout@v2
      - name: setup .Net Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet }}
      - name: set environment
        run: echo ::set-env name=workspace::$GITHUB_WORKSPACE
      - name: publish
        run: dotnet publish HardHat/HardHat.csproj -o "${{ env.workspace }}/Dist/" -c release -r win10-x64
      - name: branch
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: win
          FOLDER: ${{ env.workspace }}/Dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  mac:
    runs-on: ubuntu-latest
    name: build mac
    steps:
      - uses: actions/checkout@v2
      - name: setup .Net Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet }}
      - name: set environment
        run: echo ::set-env name=workspace::$GITHUB_WORKSPACE
      - name: publish
        run: dotnet publish HardHat/HardHat.csproj -o "${{ env.workspace }}/Dist/" -c release -r osx.10.12-x64
      - name: branch
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: mac
          FOLDER: ${{ env.workspace }}/Dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tweet:
    runs-on: ubuntu-latest
    name: tweet
    needs: [win, mac]
    steps:
      - uses: actions/checkout@v2
      - name: setup Twitter
        uses: ethomson/send-tweet-action@v1
        with:
          status: "Hard Hat - C# .NET Core Console with Android Building Tools [ Win+Mac ]\n
          New version available: ${{ env.version }} 🐛🛠\n
          \n
          https://github.com/deinsoftware/hardhat"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}